version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: increase
  ignore:
  - dependency-name: snyk
    versions:
    - 1.439.0
    - 1.440.1
    - 1.446.0
    - 1.454.0
    - 1.458.0
    - 1.461.0
    - 1.473.0
    - 1.485.0
    - 1.502.0
    - 1.511.0
    - 1.521.0
    - 1.530.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.1
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.0
    - 5.27.0
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.9.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
