language: node_js
node_js:
- '8'
before_install:
- npm install -g npm@latest
install:
- npm install
before_script:
- greenkeeper-lockfile-update
jobs:
  include:
    - stage: "Build"
      name: "Compile for distribution"
      script: npm run build
    - stage: "Test"
      name: "Unit tests"
      script: npm test && cat ./coverage/lcov.info | coveralls
    - name: "Integration tests: chrome"
      env: BROWSERS="CHROME"
      script: npm run server && npm run integration
    - name: "Integration tests: firefox"
      env: BROWSERS="FIREFOX"
      script: npm run server && npm run integration
    - name: "Integration tests: edge"
      env: BROWSERS="EDGE"
      script: npm run server && npm run integration
    - name: "Integration tests: IE11"
      env: BROWSERS="IE_11"
      script: npm run server && npm run integration
    - name: "Integration tests: IE10"
      env: BROWSERS="IE_10"
      script: npm run server && npm run integration
    - name: "Integration tests: IE9"
      env: BROWSERS="IE_9"
      script: npm run server && npm run integration
    - name: "Integration tests: safari"
      env: BROWSERS="SAFARI"
      script: npm run server && npm run integration
after_script:
- greenkeeper-lockfile-upload
addons:
  browserstack:
    forcelocal: true
    username:
      secure: Ngf992mNXzG7AWpO8c78dwpNT4CAI2pqEs++Kr/6UR+LYLy2foJJKT+TpOdM2h3iFVJAKa/dIpBHkBqU4DpQr4I0KgxShLUDKmdcforv89RCKRQCMuxaYh4rQORvbpAelCBoLS9AxscJAB8w0R2F060fEMV6Z06iiK6yf+Cxzlv6ws1q9xoUpSTh83y2jK9H3f6AwknFthzyWWnEHAebB2T1AbNXoIJCGiUvkx1V1yUkwm+z2oXjmhDUPpX2KW1nBgfRJQtGsV+V6cN+gAKvtmRqysJJDwE4k3cB4sEqlh3z1J0BDSgdGaQmipP8X2UGC1Y7YgUcIXdVxHao6P396LcRr7vvRYWt13ykkC8wjj0C1Mqn+4KQIo+UswBtb9m67mfN0SoLtaakg8W2h6wTP+E15FVumX73plhgv+2sefDAT3332wHMTRz7ggm3hgBwYVc0wkcft4bGrftzeExnQZbrzHyBBN7wqvQ39M6VxJ0RJsn11YODYPlSNkGnFmn9Od5KVXF8CDoUPfLC4qUifvItBpWBpXxjsR7vTCY6fjiv7cXxbYS5uSme5EbE5w5W6hYYgq9KC3XWJInVDj9ENXsBf+StW+ag4UUI2P5hzXvf0zfbDTE2ZY7+izQBfdbroQnns5ymrZcXgjGIPjXRvX7V8b/KfPbGPDtSod09ts0=
    access_key:
      secure: yVbT+TpTJjXyo4YhV3wy0bWU5pRqcVM1H1vUdAgAXK5Q1oXqE1h/3FKV/ZCuNja2Hc2A7C1lrOvNmswv5b4S0ERY58hMP4ajArNhXj/tbRnmy9eLHH6JczW6/0lxAAut7CpI9VvxiE8zkhPgzttZoPn2Wj6vxqIZ9xE9w3hTWWxChW8mLSIb/Sk8rS/eWiQtTREwUE9PPjqgZVwz2B5DQYNTnYMpXNm9+1H9Y5ykrXoEdXtNAUTntyUrYDvwv5I0uTadTchvO9acm9gepMjNGQjwGS24vCjqB3qLnMLW0nJmo9WiGjTQ8bxxRAkuWHm8xJ0yqGrGHq4iSgEHZUxjfb3ZIbYKrNm9646IOUabBTElVuigkJOLN6NxyHeycKNk3PCQwSApFppZZIzgUqtEdywVa6tUxQPWTHMfgClWUFVbVnlxcx5ig8KWg5X7jSlvtbgYvQftEOI5anjxzcH/+/FFvZrWCna4EYanj9vdikiaGzJczh53+ZZO25UtTmj6nvpfwDCeJnT3ecBHiUeWy6xuTtc9wamb3qeUASz9LYZOPI1DtN61TfSvehUBRxFVdMPkz8XOigOFzigSoJMhkCaMyivHQOWo3r1QTqVDym8HQ+7ZHqubJFF5X3sxuevVFvrq4HX0AyXGqGiO0VsrJH7hRj30Iq0QmJprwQ7XCD8=
env:
  global:
    secure: qi+wztUVO1oHzpadU2SFC1rS6hgMIjGFtiM88wxrvH7pPqreCH3ALVYNdnnWzoZ573CpQc6eFvJ/AtpMUBtyuutCrPFoONEv/1OFnldQlS25TKxLrViC15cx4lstSd9qJxyA8uHYXKedb80X1W7PKgIVW9ETGX2zUIWArz0Z+OhcCsEwQcR3qvAwuTl1K1cM9XMEbLM4pay9aRcNimD3HePvEGgCzrXoiZFoLRW7tL+yNqoDRSMXfb4Q5DZq+ZiIJzRCx5fHRbp6290pudJGWu8sa9XJAP1CP/jXp8R/5OFG0oIRzsgmCRGzdM//vQuCw3dcxj67xvXMCVhLbLEMww5TFyPNVpS2G0X/x1vuOB61PGBTom7EO1XT7QdV+kXHOSmi6uSJw4MVRLj8A2pQ85aKzK1hpgxEDIIG7C1rI+Re9RpBD6/BmsaFAZeeXpXwXqKD7DsRIuKhtpnsw2vptinrWcN1SANv8J3wNb+ce/1JY0EfPb0jUD96EIKuFD35uFxC5fIp9xmwaENERbxcm6rQz1liyk6VdNZu1qMedJzi0zoq7L/wTuPQQaea5rWXHiom+KLL+eQu0W797UJhcQlzN6HYiDQe+kWoGVE/TEpvf9Z2mUM7ZHr1LdhoHRoVyAURsvlmW6PhYUMMOVcv/3kJtSOt+/3gJpGpZc/OQYs=
