language: node_js
node_js:
- "8"
before_install:
 - npm install -g npm@latest
install:
  - npm ci
script:
  - npm test && cat ./coverage/lcov.info | coveralls
#  - http-server ./ &
#  - npm run integration
#addons:
#  browserstack:
#    forcelocal: true
#    username: 
#      secure: "TODO"
#    access_key:
#      secure: "TODO"
